### ISSUE TITLE
npm start无响应

### ISSUE THREAD

**Issue by tianheng2017** [LoopringSecondary/loopr#211]
administratordeMacBook-Air:loopr2 administrator$ npm start

> @ start /Users/administrator/Downloads/loopr2
> roadhog server

Unexpected token export

**Comment by hzbdesigner** [comment]
我们本地没有发现这个问题，有更多错误信息吗或者完整报错截图吗？或者试试 先 npm install 再 npm start ?

**Comment by tianheng2017** [comment]
![1](https://user-images.githubusercontent.com/29515610/38463211-d6696662-3b27-11e8-9e75-d3cc8b97aaaf.png)


一直卡在这个位置不动了

**Comment by ghost** [comment]
I've been getting this error for a while, too. The last time I successfully compiled locally was probably a little over a month ago. Not sure if this will help, but running "npm run-script build" gave this result:


`Josephs-MBP:loopr2-master josephkeeton$ npm run-script build
`
```
> @ build /Users/josephkeeton/Documents/loopr2-master
> roadhog build

```
```
Build failed: Unexpected token export
/Users/josephkeeton/Documents/loopr2-master/.webpackrc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Module._compile (/Users/josephkeeton/Documents/loopr2-master/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (/Users/josephkeeton/Documents/loopr2-master/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at getUserConfig (/Users/josephkeeton/Documents/loopr2-master/node_modules/af-webpack/lib/getUserConfig/index.js:127:14)
    at /Users/josephkeeton/Documents/loopr2-master/node_modules/roadhog/lib/build.js:41:49
    at new Promise (<anonymous>)
    at new F (/Users/josephkeeton/Documents/loopr2-master/node_modules/core-js/library/modules/_export.js:36:28)
[graceful-process#7138] exit with code:0
``
```

**Comment by tianheng2017** [comment]
是的，我也是这个错误：
administratordeMacBook-Air:loopr2 administrator$ npm run build

> @ build /Users/administrator/Downloads/loopr2
> roadhog build

Build failed: Unexpected token export
/Users/administrator/Downloads/loopr2/.webpackrc.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Module._compile (/Users/administrator/Downloads/loopr2/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:671:10)
    at Object.newLoader [as .js] (/Users/administrator/Downloads/loopr2/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at getUserConfig (/Users/administrator/Downloads/loopr2/node_modules/af-webpack/lib/getUserConfig/index.js:127:14)
    at /Users/administrator/Downloads/loopr2/node_modules/roadhog/lib/build.js:41:49
    at new Promise (<anonymous>)
    at new F (/Users/administrator/Downloads/loopr2/node_modules/core-js/library/modules/_export.js:36:28)
    at _default (/Users/administrator/Downloads/loopr2/node_modules/roadhog/lib/build.js:34:10)
[graceful-process#7382] exit with code:0

**Comment by hzbdesigner** [comment]
fixed by https://github.com/Loopring/loopr2/pull/218 .  

```
git pull xxx // get latest code
rm -rf node_modules & npm i
npm start
```
